[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/posts/2026-01-05-2025/"
  to = "/posts/2026-04-22-2025/"
  status = 301