backend:
  name: git-gateway
  branch: master
  squash_merges: true

publish_mode: editorial_workflow

display_url: https://mikeaparicio.com
logo_url: https://mikeaparicio.netlify.app//images/meta/ma-favicon.svg

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    label_singluar: "Post"
    folder: "src/posts"
    slug: "{{date}}-{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    sortableFields: ['date','commit_date', 'title']
    view_filters:
      - label: "Posts this year"
        field: date
        pattern: "2020"
      - label: "Drafts"
        field: draft
        pattern: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false, pickerUtc: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Image Alt Text", name: "thumbnailAlt", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
