name: Poll Letterboxd RSS and Trigger Netlify Build

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger via GitHub Actions UI

jobs:
  poll:
    runs-on: ubuntu-latest
    concurrency: poll-letterboxd # Prevents multiple instances from running at the same time
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Dependencies
        run: npm install

      - name: Run Poll Script
        run: node pollLetterboxd.js
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}

      - name: Commit and Push Updated movies.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _src/_data/movies.json
          git status # Debugging step to check if files are staged
          git diff --staged # Show what changed
          git commit -m "Auto-update movies.json from Letterboxd" || echo "No changes to commit"
          git push origin main || echo "No changes to push"


      - name: Trigger Netlify Build
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
