name: Poll Letterboxd RSS and Trigger Netlify Build

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger via GitHub Actions UI

jobs:
  poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Ensures we can push changes

      - name: Install Dependencies
        run: npm install

      - name: Run Poll Script
        run: node pollLetterboxd.js
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}

      - name: Commit and Push Updated movies.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _src/_data/movies.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update movies.json with latest Letterboxd data"
          git push origin main
