name: Poll Letterboxd RSS and Trigger Netlify Build

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Poll Script
        run: node pollLetterboxd.js
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
